name: chitchat   # Flutter project name (internal, do not change unless needed)
description: "ChitChat Flutter Project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.9
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.11
  firebase_messaging: ^15.2.10
  googleapis_auth: ^2.0.0
  intl: ^0.20.2
  google_sign_in: ^6.2.1
  google_generative_ai: ^0.4.7
  emoji_picker_flutter: ^4.3.0
  lottie: ^3.3.1
  flutter_notification_channel: ^3.1.1
  cached_network_image: ^3.4.1
  gallery_saver_plus: ^3.2.9
  flutter_dotenv: ^6.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rename_app: ^1.3.2  # For renaming app/package
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - secrets/service-account-key.json
    - assets/
    - assets/images/
    - assets/lottie/

# Launcher icon config
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"
