// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpXbf4mYnHpTz2gj38L89XPgP-Jvz00-g',
    appId: '1:590100334603:web:0f793fda9db81f7a4cdf0e',
    messagingSenderId: '590100334603',
    projectId: 'zingchat-88917',
    authDomain: 'zingchat-88917.firebaseapp.com',
    storageBucket: 'zingchat-88917.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOVZRS95XK0reGsmLx0nGfgdygSdy9IVk',
    appId: '1:590100334603:android:8ac69cbe8c4401044cdf0e',
    messagingSenderId: '590100334603',
    projectId: 'zingchat-88917',
    storageBucket: 'zingchat-88917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn3HozIae31JhcfYEGnxU3lh3FbSE06c0',
    appId: '1:590100334603:ios:e07bacb2573eada34cdf0e',
    messagingSenderId: '590100334603',
    projectId: 'zingchat-88917',
    storageBucket: 'zingchat-88917.firebasestorage.app',
    iosBundleId: 'com.example.zingchat',
  );

}