// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOVZRS95XK0reGsmLx0nGfgdygSdy9IVk',
    appId: '1:590100334603:android:4f47b00e79c23b334cdf0e',
    messagingSenderId: '590100334603',
    projectId: 'zingchat-88917',
    storageBucket: 'zingchat-88917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn3HozIae31JhcfYEGnxU3lh3FbSE06c0',
    appId: '1:590100334603:ios:92b25eaefa799b254cdf0e',
    messagingSenderId: '590100334603',
    projectId: 'zingchat-88917',
    storageBucket: 'zingchat-88917.firebasestorage.app',
    iosClientId: '590100334603-ulhv5cllatgk5u34emkl92kjfonloub5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnanDOVN976RBDzRR5X0YmzWQMyKegVCg',
    appId: '1:554413408008:web:4067e63eb1fc2b92b736bd',
    messagingSenderId: '554413408008',
    projectId: 'sandesh-6018b',
    authDomain: 'sandesh-6018b.firebaseapp.com',
    storageBucket: 'sandesh-6018b.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBHRcT50ppHd2DboOwKljanN8oi2EwJFg',
    appId: '1:554413408008:ios:939f3c37bdb6fa31b736bd',
    messagingSenderId: '554413408008',
    projectId: 'sandesh-6018b',
    storageBucket: 'sandesh-6018b.firebasestorage.app',
    androidClientId: '554413408008-3p7qsp99be69go0ieeo0ekm8e915m91v.apps.googleusercontent.com',
    iosClientId: '554413408008-h4m9qv3iplgu6in4k4qva40uimmskbm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnanDOVN976RBDzRR5X0YmzWQMyKegVCg',
    appId: '1:554413408008:web:edb1514bdfbf4e46b736bd',
    messagingSenderId: '554413408008',
    projectId: 'sandesh-6018b',
    authDomain: 'sandesh-6018b.firebaseapp.com',
    storageBucket: 'sandesh-6018b.firebasestorage.app',
  );

}